### ISSUE TITLE
showPrevNext does nothing in Detail.html

### ISSUE THREAD

**Issue by scibile** [georgringer/news#183]
showPrevNext = 1 does activate the condition <f:if condition="{settings.detail.showPrevNext}">
but the n:simplePrevNext viewhelper does not produce any output {paginated}

**Comment by georgringer** [comment]
Which news version are you using?
The VH considers only news with the same pid, maybe that is the problem?

**Comment by scibile** [comment]
I use the last version in the TER, (5.3.1) not the dev here from the github, and no, the news is all from the same PID ... if you know of issues resolved in this dev version I can try to use this github version before trying anything else ... as extra feedback, I use EXT:t3sbootstrap, it does not report any conflict but it could have influence ...

**Comment by scibile** [comment]
maybe you need to know also the typo3 version, still with 7, the last one though v7.6.14

**Comment by georgringer** [comment]
Do the news records have a date filled? otherwise it won't work. Basically what it does: select news records which have a higher and lower date and the same pid

**Comment by scibile** [comment]
Sorry georg ... the problem is solved but I have no clue why I did not work in the first place, nor what happened that solved it, I actually had not looked at it anymore for some time and noticed all of a sudden that the news displayed a next and previous ... probably something with caching, probably not a proper bug report but inapt use of typo3, I hope you did not lose much time over it

**Comment by georgringer** [comment]
thanks for your feedback! all fine! have a nice 2017!

**Comment by Hobokens** [comment]
I'm sorry. I have the same problem with TYPO3 7.6.14 and the newest version of news from github. I've set
    `plugin.tx_news.settings.detail.showPrevNext = 1`
in setup.txt but the navigation remains hidden 
`<li class="previous" style="display: none;">`
All news have the same pid and different datetime.

Thanks for the fantastic extension and have a great year 2017!

**Comment by nannione** [comment]
This still happens probably in all versions if you have news records with the exact same date. I came across this when i just duplicated some records while developing. This is very unlikely to happen in a live environment. As Georg said the VH considers: "... news records which have a **higher and lower** date and the same pid."
